/**:
  ros__parameters:
    video_device: "/dev/video0"
    image_width: 1024
    image_height: 576
    pixel_format: "yuyv"
    framerate: 10.0
    brightness: 100
    camera_name: "button_cam"


# /**:
  # ros__parameters:
    # video_device: "/dev/video0"
    # image_width: 1920
    # image_height: 1080
    # pixel_format: "yuyv"
    # framerate: 30.0
    # brightness: 100
    # camera_name: "button_cam"